
[package]
name = "game"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy = {workspace = true}

bevy_common_assets = {workspace = true} 

bevy_ggrs = {workspace = true}
ggrs = {workspace = true}

leafwing-input-manager = {workspace = true}

thiserror = {workspace = true}

rand = {workspace = true}

serde ={workspace = true} 
serde_json = {workspace = true}
once_cell = {workspace = true}
pathfinding = {workspace = true}


utils = { path = "../utils"}
animation ={ path = "../animation"}

[dev-dependencies]
bevy-inspector-egui = {workspace = true}

