name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'examples/**'
      - 'website/**'
      - 'crates/**'
      - 'Cargo.toml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
          - name: Check out
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Dependency
        run: sudo apt-get install g++ make pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev && rustup component add rustfmt
      - name: Dependencies
        run: cargo vendor && make dep_web
      - name: Build web
        run: make build_website TARGET=web PROFILE=prod
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: website/
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
  #release_dev:
  #  runs-on: macos-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: rustup
  #    run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && rustup default nightly-2022-04-13 && cargo install --force cargo-make && cd game && cargo make build-native
  #  - name: Create release folder
  #    run: mkdir -p release && cp ./game/target/debug/cod-zombie-2d-clone ./release
  #  - uses: "marvinpinto/action-automatic-releases@latest"
  #    with:
  #      repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #      automatic_release_tag: "latest"
  #      prerelease: true
  #      title: "Development Build macos"
  #      files: |
  #        ./release/*